@startuml
title Sequence Diagram
Game -> Text : getInstruction()
Text --> Game : GameInstruction[ask name text]
Game -> Text : getInstruction()
Text --> Game : GameInstruction[press enter]
loop while balance < 3000

Game -> PlayerTurn : play()
PlayerTurn -> Cup : sumDice()
Cup -> Die : throw()
Die --> Cup : faceValue
Cup --> PlayerTurn : currentSum
PlayerTurn -> Text : description[currentSum]
Text -> PlayerTurn : description
PlayerTurn -> Square : pointsValue[currentSum]
Square --> PlayerTurn : pointsValue
loop if deposit
PlayerTurn -> Player : deposit()
Player -> BankAccount : setBalance()
end
loop else if withdraw
PlayerTurn -> Player : withdraw()
Player -> BankAccount : setBalance()
end
BankAccount --> Player : newBalance
Player --> PlayerTurn : newBalance


end

@enduml